### ISSUE TITLE
Remote dependency diagnostics is not working

### ISSUE THREAD

**Issue by I3undy** [Lombiq/Orchard-Azure-Application-Insights#1]
@Piedone created on Mar 9, 2015: 
https://orchardazureappinsights.codeplex.com/workitem/2

The issue is that RemoteDependencyModule will always try to load the necessary native binaries from Orchard.Web/bin, what can't be supported from a module. Needs configuration or something in the AI SDK. 

Check with future SDK updates.

**Comment by Piedone** [comment]
This is fixed in the latest source now.
