### ISSUE TITLE
Is there an Orchard Core Version?

### ISSUE THREAD

**Issue by nogginbox** [Lombiq/Orchard-Azure-Application-Insights#11]
Do you have any plans to port this to Orchard Core?

**Comment by Piedone** [comment]
Yes! What's more, it's already fully done. But there's a bit of administration to be done before open-sourcing it since it was for a client project. We hope to get that done soon.

**Comment by nogginbox** [comment]
That is good news. I look forward to trying it out. Please let me know when it's ready.

**Comment by Piedone** [comment]
In the dev branch now :).

**Comment by 0liver** [comment]
That's awesome.
