### ISSUE TITLE
NuGet version

### ISSUE THREAD

**Issue by deanmarcussen** [Lombiq/Orchard-Azure-Application-Insights#15]
Any chance this will make it to NuGet at some point?

Or is it already on a feed somewhere, that I couldn't see?

**Comment by Piedone** [comment]
Yes, once OC 1.0 is out we'll start publishing all our extensions to NuGet as well. Stay tuned!

**Comment by msc2402** [comment]
Hey,

Any update on the NuGet packages?

Ty!

**Comment by Piedone** [comment]
Not yet, sorry, but we'll do it as soon as we find the time.

**Comment by Piedone** [comment]
Work on this is tracked here: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/23

**Comment by Piedone** [comment]
We've published a preview NuGet package: https://www.nuget.org/packages/Lombiq.Hosting.Azure.ApplicationInsights/ Could you check, please?
