### ISSUE TITLE
ShellSettings reporting wrong name

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Orchard-Azure-Application-Insights#19]
See the original issue reported by @markgould here: https://github.com/OrchardCMS/OrchardCore/issues/10778

**Comment by markgould** [comment]
Thank you for fixing this so quickly!

**Comment by Piedone** [comment]
No problem. Please check out if it works for you too. I'm also deploying it to [DotNest](https://dotnest.com/).

**Comment by markgould** [comment]
Looks like it works, thanks! I'm about to deploy it to our environment and will keep an eye on it.
