### ISSUE TITLE
Simplify request tracking once WebOperationIdTelemetryInitializer is open

### ISSUE THREAD

**Issue by I3undy** [Lombiq/Orchard-Azure-Application-Insights#2]
@Piedone created on Mar 9, 2015: 
https://orchardazureappinsights.codeplex.com/workitem/3

Microsoft.ApplicationInsights.Extensibility.Web.TelemetryInitializers.WebOperationIdTelemetryInitializer in Microsoft.ApplicationInsights.Extensibility.Web is internal and thus cannot be re-used. That's why we have our own WebOperationIdTelemetryInitializer. 

Once the built-in will be opened we can remove the custom implementation.

**Comment by Piedone** [comment]
Isn't needed in the latest library with .NET Core anymore.
