### ISSUE TITLE
Migrate from instrumentation keys to connection strings

### ISSUE THREAD

**Issue by rjpowers10** [Lombiq/Orchard-Azure-Application-Insights#34]
Hi, I know March 2025 is almost three years away so there's not really a rush, but I was wondering if there are plans to move this module to using connection strings.

![image](https://user-images.githubusercontent.com/68876423/169578742-f6147ca1-d341-4aa7-9165-f2edb9cb237c.png)

[Connection strings](https://docs.microsoft.com/en-us/azure/azure-monitor/app/sdk-connection-string?tabs=net#overview)

[Migration doco](https://docs.microsoft.com/en-us/azure/azure-monitor/app/migrate-from-instrumentation-keys-to-connection-strings)

**Comment by Piedone** [comment]
Since the module exposes all configuration options built into the .NET AI library, you should be able to just write this:

```json5
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      //...
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
  },
  "OrchardCore": {
    //...
  },
  "ApplicationInsights": {
    "ConnectionString": "your connection string comes here"
  }
}
```

Doesn't this work for you? We should update the docs to recommend this though.

**Comment by rjpowers10** [comment]
> Since the module exposes all configuration options built into the .NET AI library, you should be able to just write this:
> Doesn't this work for you? We should update the docs to recommend this though.

My mistake! I didn't realize the "ApplicationInsights" section was the plain old AI options, so changing to "ConnectionString" did work.

I'll leave this issue open as a reminder to update the docs.
