### ISSUE TITLE
After enabling, nothing showing up

### ISSUE THREAD

**Issue by I3undy** [Lombiq/Orchard-Azure-Application-Insights#5]
**andrewconnell** created on Oct 4, 2015: 
https://orchardazureappinsights.codeplex.com/workitem/8

Not sure what's going on... once I've added this module and the dependent helpful libraries module, I've enabled them with no errors. However, even after resetting the web server, I'm not seeing anything in the /admin/settings page to enter the key for my App Insights. 

Ideas?

**Comment by I3undy** [comment]
@Piedone commented on Oct 8, 2015:

So you don't see "Azure Application Insights" under the Settings menu in the admin? What happens if you open /Admin/Settings/AzureApplicationInsightsSettings? Are there any errors in the log?

**Comment by Piedone** [comment]
Closing because of no reply.
