### ISSUE TITLE
Azure Application Insights menu not showing in settings?

### ISSUE THREAD

**Issue by LivyChops** [Lombiq/Orchard-Azure-Application-Insights#8]
@Piedone Hi there, forgive my ignorance - but I'm running 1.10.1 and have enabled your module to no effect. Am I expecting an 'Azure Application Insights' menu to be added to Dashboard > Settings Menu? Or do I have to perform some additional steps (for wouldn't that require:
`Filters.Add(new TemplateFilterForPart<AzureApplicationInsightsTelemetrySettingsPart>("AzureApplicationInsightsTelemetrySettings", "Parts/AzureApplicationInsightsTelemetrySettings", "Azure Application Insights"));`
..to be added to the handler)? 
Thanks in advance, Liv

**Comment by Piedone** [comment]
Yes, you should see the settings menu there. My guess would be that you didn't put the module into a folder called exactly "Lombiq.Hosting.Azure.ApplicationInsights": using the same module folder name as the module's ID (which is commonly also the same as its csproj's) is needed for all Orchard extensions.

**Comment by shonuff3d** [comment]
I'm also not seeing this popup when i activate. I don't get any errors either.. just doesn't appear anywhere. I've verified my folder structure is correct. I'm running on 1.9.3 orchard as well. Any insight beyond the above?

**Comment by Piedone** [comment]
Only that the current version of the module was never tested with 1.9.3 (but 1.10.x) so there might be some incompatibility issues (though those should also show up in the log).

**Comment by shonuff3d** [comment]
Ahh bummer. Ok.. we haven't fully migrated to 1.10.0 as of yet. Will hold off then.

**Comment by Piedone** [comment]
So unless told otherwise this seems to be not an issue with the module.
